<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA7v9Ya7\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA7v9Ya7/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerA7v9Ya7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerA7v9Ya7\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerA7v9Ya7\srcApp_KernelProdContainer([
    'container.build_hash' => 'A7v9Ya7',
    'container.build_id' => '24d14148',
    'container.build_time' => 1635170698,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA7v9Ya7');
