<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Nationnalite extends \App\Entity\Nationnalite implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Nationnalite' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Nationnalite' . "\0" . 'nomNatio', '' . "\0" . 'App\\Entity\\Nationnalite' . "\0" . 'agents', '' . "\0" . 'App\\Entity\\Nationnalite' . "\0" . 'cibles', '' . "\0" . 'App\\Entity\\Nationnalite' . "\0" . 'contacts', '' . "\0" . 'App\\Entity\\Nationnalite' . "\0" . 'Pays'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Nationnalite' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Nationnalite' . "\0" . 'nomNatio', '' . "\0" . 'App\\Entity\\Nationnalite' . "\0" . 'agents', '' . "\0" . 'App\\Entity\\Nationnalite' . "\0" . 'cibles', '' . "\0" . 'App\\Entity\\Nationnalite' . "\0" . 'contacts', '' . "\0" . 'App\\Entity\\Nationnalite' . "\0" . 'Pays'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Nationnalite $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomNatio(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomNatio', []);

        return parent::getNomNatio();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomNatio(string $nomNatio): \App\Entity\Nationnalite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomNatio', [$nomNatio]);

        return parent::setNomNatio($nomNatio);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgents(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgents', []);

        return parent::getAgents();
    }

    /**
     * {@inheritDoc}
     */
    public function addAgent(\App\Entity\Agent $agent): \App\Entity\Nationnalite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAgent', [$agent]);

        return parent::addAgent($agent);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAgent(\App\Entity\Agent $agent): \App\Entity\Nationnalite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAgent', [$agent]);

        return parent::removeAgent($agent);
    }

    /**
     * {@inheritDoc}
     */
    public function getCibles(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCibles', []);

        return parent::getCibles();
    }

    /**
     * {@inheritDoc}
     */
    public function addCible(\App\Entity\Cible $cible): \App\Entity\Nationnalite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCible', [$cible]);

        return parent::addCible($cible);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCible(\App\Entity\Cible $cible): \App\Entity\Nationnalite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCible', [$cible]);

        return parent::removeCible($cible);
    }

    /**
     * {@inheritDoc}
     */
    public function getContacts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContacts', []);

        return parent::getContacts();
    }

    /**
     * {@inheritDoc}
     */
    public function addContact(\App\Entity\Contact $contact): \App\Entity\Nationnalite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContact', [$contact]);

        return parent::addContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContact(\App\Entity\Contact $contact): \App\Entity\Nationnalite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContact', [$contact]);

        return parent::removeContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getPays(): ?\App\Entity\Pays
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPays', []);

        return parent::getPays();
    }

    /**
     * {@inheritDoc}
     */
    public function setPays(?\App\Entity\Pays $Pays): \App\Entity\Nationnalite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPays', [$Pays]);

        return parent::setPays($Pays);
    }

}
